#!/bin/sh
### BEGIN INIT INFO
# Provides: indiestor-pro-watch
# Required-Start: $all
# Required-Stop: $all
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

case "$1" in
  start)
	echo "Start indiestor pro watching"
	indiestor-pro --services -start-watching
    ;;
  stop)
	echo "Stop indiestor pro watching"
	indiestor-pro --services -stop-watching
    ;;

  *)
    echo "Usage: /etc/init.d/indiestor-pro-watch-avid-workspace {start|stop}"
    exit 1
    ;;
esac

exit 0

