#!/bin/sh
# postinst script for indiestor-pro
#
# see: dh_installdeb(1)

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    configure)
	indiestorProUsers=$(cat /etc/group | grep "indiestor-pro-users")
	if [ -z "$indiestorProUsers" ]; then
		groupadd "indiestor-pro-users"
	fi
	indiewheel=$(cat /etc/group | grep indiewheel)
	if [ -z "$indiewheel" ]; then
		groupadd indiewheel
	fi
	indienotifypro=$(cat /etc/passwd | grep indienotify-pro)
	if [ -z "$indienotifypro" ]; then
		adduser --system --group indienotify-pro
	fi

	# setup directories
	rm -r/etc/indiestor-pro/res
    mkdir -p /var/spool/indiestor-pro
    chown -R indienotify-pro /var/spool/indiestor-pro

    # update share definitions & refresh stats
    echo "updating share defintions and usage stats. Please wait... "
	indiestor-pro --services -refresh-share-definitions
	indiestor-pro --services -refresh-usage-stats
	indiestor-pro --services -start-watching

    # start watching
	update-rc.d indiestor-pro-watch-avid-workspace defaults

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0

