#!/bin/sh
# postinst script for indiestor-pro
#
# see: dh_installdeb(1)

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    configure)
	indiestorProUsers=$(cat /etc/group | grep "indiestor-pro-users")
	if [ -z "$indiestorProUsers" ]; then
		groupadd "indiestor-pro-users"
	fi
	indiewheel=$(cat /etc/group | grep indiewheel)
	if [ -z "$indiewheel" ]; then
		groupadd indiewheel
	fi
	indienotify=$(cat /etc/passwd | grep indienotify)
	if [ -z "$indienotify" ]; then
		adduser --system --group indienotify
	fi
	/etc/init.d/incron restart
	nmbd restart
	smbd restart
        echo /var/spool/indiestor-pro IN_CREATE /usr/bin/indiestor-pro-inotify | incrontab -u indienotify -
        mkdir -p /var/spool/indiestor-pro
        chown -R indienotify /var/spool/indiestor-pro
	indiestor-pro --services -start-watching
	release=$(lsb_release -a | grep Codename | sed 's/Codename:\t\(.*\)/\1/')
	if [ "$release" = "wheezy" ] ; then
		insserv indiestor-pro-watch-avid-workspace
	else
		update-rc.d indiestor-pro-watch-avid-workspace defaults
	fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0

